use std::path::Path;
use std::{env, fs};

fn main() {
    // Generate a list of all available map files to embed in the binary
    println!("cargo:rerun-if-changed=./maps");

    let output_path = Path::new("map_files.rs.inc");

    let mut output = String::new();
    output.push_str("// This file is automatically generated by build.rs\n");
    output.push_str("{\n");
    output.push_str("    let mut map_files = std::collections::HashMap::new();\n");

    if let Ok(map_files) = fs::read_dir("./maps") {
        for map_file in map_files {
            let path = map_file.unwrap().path();
            if let Some(extension) = path.extension() {
                if extension == "map" {
                    if let Ok(abs_path) = fs::canonicalize(&path) {
                        output.push_str(&format!(
                            "    map_files.insert(\"{}\", include_str!(\"maps/{}\"));\n",
                            path.file_stem().unwrap().to_str().unwrap(),
                            abs_path.file_name().unwrap().to_str().unwrap()
                        ));
                    }
                }
            }
        }
    }

    output.push_str("    map_files\n}");

    fs::write(output_path, output).expect("Failed to write map_files.rs.inc");

    println!("cargo:rerun-if-changed=../.git/HEAD");

    if env::var_os("CARGO_CFG_WINDOWS").is_some() {
        winresource::WindowsResource::new()
            .set_icon("../docs/images/snow.ico")
            .compile()
            .expect("Failed to embed icon (Windows)");
    }
}
