name: Checks and tests

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - 'README.md'
      - 'docs/**'
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - 'README.md'
      - 'docs/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Update package repos
      run: sudo apt-get -y update
    - name: Install prerequisites
      run: sudo apt-get -y install libsdl2-dev
    - name: Install cargo-llvm-cov
      uses: taiki-e/install-action@cargo-llvm-cov
    - name: Fetch submodules
      run: git submodule update --init --recursive
    - name: Code formatting check
      run: cargo fmt --check
    - name: Clippy lint
      run: cargo clippy --all -- -D warnings
    - name: Generate test data
      working-directory: ./testdata/m68000
      run: python3 decode.py
    - name: Test build with no features
      run: cargo build --no-default-features --all
    - name: Test build core with no features
      run: cargo build --no-default-features -p snow_core
    - name: Generate code coverage
      # snow_frontend_egui excluded due to https://github.com/Smithay/wayland-rs/issues/717
      run: cargo llvm-cov --workspace --exclude snow_frontend_egui --codecov --output-path codecov.json
    - name: Test snow_frontend_egui separately
      run: cargo test --bin snow_frontend_egui
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: codecov.json
        fail_ci_if_error: false

